apiVersion: v1
kind: Service
metadata:
  name: sample-web-app-2
spec:
  selector:
    app: sample-web-app-2
  ports:
  - protocol: TCP
    port: 8099
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-web-app-2
  template:
    metadata:
      labels:
        app: sample-web-app-2
    spec:
      containers:
      - name: sample-web-app-2
        image: nginx:latest
        ports:
        - containerPort: 80
